version: '3.8'

services:
  options-pricing-app:
    build: .
    container_name: options-pricing-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1